# Generated by Django 3.1.4 on 2020-12-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.CharField(default='', max_length=9, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=30)),
                ('body', models.CharField(default='', max_length=1200)),
                ('datePassed', models.BooleanField(default=False)),
            ],
        ),
    ]
