# Generated by Django 3.1.4 on 2020-12-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201207_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
