# Generated by Django 3.1.4 on 2020-12-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201207_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
