# Generated by Django 3.1.4 on 2020-12-08 00:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201207_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=9, unique=True),
        ),
    ]
