# Generated by Django 3.1.4 on 2020-12-08 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_journalentry_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=40),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
